
/*
* MAPS TO RESOURCE NAMES PROVIDED BY THE API
*/
export enum ResourceName {
    PLATFORM_HOME = "PLATFORM_HOME",
    SIGN_UP_GOOGLE = "SIGN_UP_GOOGLE",
    LOGIN = "LOGIN", 
    USER_HOME = "USER_HOME",
    USER_ACTIVITY = "USER_ACTIVITY",
    USER_WALLET = "USER_WALLET",
}